"""Iterated self-play: the agent learns from its own games, generation by generation.

    .venv/bin/python analysis/self_play_loop.py --generations 3 --games 200

The hand-set weights in `analysis/evaluation.py` are scaffolding to get the
first generation off the ground. They are not meant to survive. This loop is
how they get replaced by something learned from play:

    generation N agent  ->  plays games  ->  fit weights on those outcomes
                        ->  benchmark candidate vs incumbent
                        ->  promote ONLY if it wins  ->  generation N+1

## Why the benchmark gate is not optional

The first attempt at this skipped it, accepting a candidate on held-out Brier.
That candidate predicted better (0.1815 -> 0.1666) and *lost* 14-26 when it
actually played. Prediction is not control. Every generation here has to win
games to be promoted, and a generation that fails to improve is reported and
discarded rather than quietly installed.

## Why self-play data beats random data

The weights fitted on random games learned correlations, not causes -- most
visibly `hand_diff` coming out negative, because random agents accumulate
cards they cannot play. Data generated by a competent agent does not contain
that artefact, and the positions it visits are the positions the agent will
actually face. That is the distribution-shift problem, closed by construction.

The end state is an agent whose evaluation came entirely from its own games.
This loop is the mechanism; the hand-set prior is only generation 0.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agents.greedy_agent import GreedyAgent  # noqa: E402
from agents.random_agent import RandomAgent  # noqa: E402
from analysis.benchmark import duel, interval  # noqa: E402
from analysis.evaluation import (  # noqa: E402
    FEATURE_NAMES,
    WEIGHTS_PATH,
    Model,
    features,
    load_model,
    save_model,
)
from analysis.fit_weights import brier, fit  # noqa: E402
from cards.database import load as load_db  # noqa: E402
from engine.setup import build_state, load_deck  # noqa: E402

HISTORY = Path(__file__).resolve().parent / "generations.json"
MAX_STEPS = 40_000


def play_and_sample(seed, d0, d1, db, make_agent, stride=3):
    """One self-play game between two copies of the current agent."""
    state = build_state(d0, d1, seed=seed, db=db, validate_decks=False)
    agents = (make_agent(seed), make_agent(seed + 104729))
    vectors, steps = [], 0
    while not state.is_terminal():
        if steps >= MAX_STEPS:
            return []
        if steps % stride == 0:
            values = features(state, 0)
            vectors.append([values[name] for name in FEATURE_NAMES])
        state.apply(agents[state.current_player].act(state))
        steps += 1
    label = state.returns()[0]
    return [(vector, label) for vector in vectors]


def generation(index, model, args, db, decks) -> dict:
    """One full cycle: play, fit, benchmark, decide."""
    d0, d1 = decks
    print(f"\n=== generation {index} ===")

    # Generation 0 seeds from random play; after that the agent plays itself,
    # so the training positions are the ones it will actually meet.
    if index == 0:
        make_agent = lambda s: RandomAgent(s)          # noqa: E731
        source = "random"
    else:
        make_agent = lambda s: GreedyAgent(s, model, epsilon=args.epsilon)  # noqa: E731
        source = f"greedy(gen {index - 1}), epsilon={args.epsilon}"
    print(f"playing {args.games} games with {source}…")

    per_game = []
    for i in range(args.games):
        rows = play_and_sample(args.seed + index * 10_000 + i, d0, d1, db, make_agent)
        if rows:
            per_game.append(rows)
    if len(per_game) < 8:
        print(f"  only {len(per_game)} usable games; stopping")
        return {"generation": index, "promoted": False, "reason": "not enough games"}

    split = int(len(per_game) * (1 - args.test_frac))
    train = [r for g in per_game[:split] for r in g]
    test = [r for g in per_game[split:] for r in g]
    candidate = fit(train, args.epochs, args.lr, args.l2, args.seed + index)

    before, after = brier(model, test), brier(candidate, test)
    print(f"  held-out Brier {before:.4f} -> {after:.4f}")

    # The gate that matters: does it win?
    print(f"  benchmarking candidate vs incumbent over {args.bench} games…")
    score, wins, losses, draws = duel(
        lambda s: GreedyAgent(s, candidate),
        lambda s: GreedyAgent(s, model),
        args.bench, args.seed + 777 + index, decks, db,
    )
    low, high = interval(score, wins + losses + draws)
    print(f"  candidate scores {score:.3f} ({wins}-{losses}-{draws}), 95% {low:.3f}-{high:.3f}")

    promoted = low > 0.5   # the whole interval must clear even, not just the mean
    record = {
        "generation": index,
        "trained_on_games": len(per_game),
        "brier_before": before,
        "brier_after": after,
        "bench_score": score,
        "bench_record": [wins, losses, draws],
        "bench_interval": [low, high],
        "promoted": promoted,
        "at": datetime.now(timezone.utc).isoformat(),
    }
    if promoted:
        save_model(Model(weights=candidate.weights, bias=candidate.bias,
                         fitted=True, trained_on_games=len(per_game)))
        print(f"  PROMOTED -> {WEIGHTS_PATH.name}")
    else:
        print("  NOT promoted: the candidate did not beat the incumbent "
              "convincingly. Prediction quality alone is not enough.")
    return record


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--generations", type=int, default=3)
    ap.add_argument("--games", type=int, default=150, help="self-play games per generation")
    ap.add_argument("--bench", type=int, default=40, help="benchmark games per generation")
    ap.add_argument("--epsilon", type=float, default=0.15,
                    help="exploration while generating data; without it the agent "
                         "only ever sees the lines it already prefers")
    ap.add_argument("--seed", type=int, default=2000)
    ap.add_argument("--epochs", type=int, default=12)
    ap.add_argument("--lr", type=float, default=0.30)
    ap.add_argument("--l2", type=float, default=1e-4)
    ap.add_argument("--test-frac", type=float, default=0.25)
    ap.add_argument("--deck0", default="jinx_chaos_fury")
    ap.add_argument("--deck1", default="volibear_body_fury")
    args = ap.parse_args(argv)

    db = load_db()
    decks = (load_deck(args.deck0), load_deck(args.deck1))
    history = json.loads(HISTORY.read_text()) if HISTORY.exists() else []

    for index in range(args.generations):
        model = load_model()
        record = generation(index, model, args, db, decks)
        history.append(record)
        HISTORY.write_text(json.dumps(history, indent=2) + "\n")
        if not record.get("promoted"):
            print("\nstopping: a generation that does not improve ends the run.")
            break

    promoted = sum(1 for r in history if r.get("promoted"))
    print(f"\n{promoted}/{len(history)} generations promoted; history in {HISTORY.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
