"""Generate a trajectory dataset from baseline agents (BUILD.md sections 20, 31).

Section 20 asks for games generated by the baseline agents to pretrain on, and
section 31 exposes it as `ai generate --games N`. This is the driver: it plays
games and streams them into one gzipped trajectory file.

Two details that matter for the data rather than the code:

**Seats alternate by game index.** A dataset where one policy always moves
first teaches the model that seat 0 is stronger, which is a fact about the
generator and not about Riftbound.

**The agent pairing is recorded in the header.** Data generated by
Random-vs-Random and data generated by Greedy-vs-ISMCTS are different
distributions, and mixing them without knowing is how a training run becomes
unexplainable. `provenance` already pins the engine, rules and card pool; this
adds who was playing.
"""

from __future__ import annotations

import time
from pathlib import Path

from engine.setup import build_state, load_deck
from cards.database import load as load_pool
from learning.action_encoding import ActionEncoder
from learning.trajectory import TrajectoryWriter, record_into


def generate(
    path: str | Path,
    games: int,
    agent_factories: tuple,
    decks: tuple[str, str] = ("jinx_chaos_fury", "volibear_body_fury"),
    seed0: int = 0,
    action_cap: int = 3000,
    progress: int = 0,
    log=print,
) -> dict:
    """Write `games` games into one trajectory file. Returns a summary."""
    db = load_pool()
    deck0, deck1 = load_deck(decks[0]), load_deck(decks[1])
    encoder = ActionEncoder()
    started = time.time()
    decisions = 0
    results = [0, 0, 0]  # p0 wins, p1 wins, draws

    with TrajectoryWriter(path, encoder=encoder, db=db, decks=decks) as writer:
        writer._emit({
            "record": "generator",
            "agents": [factory.__name__ if hasattr(factory, "__name__")
                       else str(factory) for factory in agent_factories],
            "games": games,
            "seed0": seed0,
            "seats_alternate": True,
        })
        for index in range(games):
            seed = seed0 + index
            state = build_state(deck0, deck1, seed=seed, db=db)
            first, second = agent_factories
            # Alternate seats so neither policy is measured only on the play.
            agents = ([first(seed), second(seed + 1)] if index % 2 == 0
                      else [second(seed), first(seed + 1)])
            before = state
            state = record_into(
                writer, state, agents, game_id=f"g{seed}",
                encoder=encoder, action_cap=action_cap,
            )
            del before
            if state.winner is None:
                results[2] += 1
            else:
                results[state.winner] += 1
            if progress and (index + 1) % progress == 0:
                rate = (index + 1) / max(1e-9, time.time() - started) * 60
                log(f"  {index + 1}/{games}  {rate:.0f} games/min")

    wall = time.time() - started
    summary = {
        "path": str(path),
        "games": games,
        "wall_seconds": round(wall, 1),
        "games_per_minute": round(games / wall * 60, 1) if wall else 0.0,
        "p0_wins": results[0],
        "p1_wins": results[1],
        "draws": results[2],
        "bytes": Path(path).stat().st_size,
    }
    summary["bytes_per_game"] = summary["bytes"] // max(1, games)
    return summary
